modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Alvaro842DEV/AsyncLocator-Refined/issues"
displayURL = "https://modrinth.com/mod/async-locator-refined"
license = "MIT"

[[mixins]]
config = "asynclocator.mixins.json"

[[mods]]
modId = "asynclocator"
version = "${version}"
displayName = "AsyncLocator-Refined"
authors = "bright_spark, alvaro842 (maintainer)"
description = "Changes the searching of features to be asynchronous to mitigate associated lag"
displayTest = "IGNORE_SERVER_VERSION"

[[dependencies.asynclocator]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.asynclocator]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"
